title: JackShen Portfolio

author: JackShen

description: Portfolio with my best projects

logo: https://raw.githubusercontent.com/jackshendrikov/jackshendrikov.github.io/master/img/intro.webp

google_analytics: G-6YW2L42J25

url: https://jackshendrikov.github.io

baseurl: ""

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md